chore: fmt hooks with shfmt + minor update
Signed-off-by: Aaron Pham <29749331+aarnphm@users.noreply.github.com>

diff --git a/hooks/commit-msg b/hooks/commit-msg
--- a/hooks/commit-msg
+++ b/hooks/commit-msg
@@ -1,7 +1,8 @@
-#!/bin/sh
+#!/usr/bin/env bash
+
 if ! head -1 "$1" | grep -qE "^(feat|fix|ci|chore|docs|test|style|refactor|perf|build|revert)(\(.+?\))?: .{1,}$"; then
-    echo "Aborting commit. Please use <type>([optional scope]): <description> format for your commit title, where <type> should be one of (feat|fix|ci|chore|docs|test|style|refactor|perf|build|revert)" >&2
-    echo 'Some valid examples: "feat: add support for PyTorch" and "fix(cli): add missing arguments of bentoml serve"'
-    echo "You can read more details about commit message formatting in DEVELOPMENT.md "
-    exit 1
+	echo "Aborting commit. Please use <type>([optional scope]): <description> format for your commit title, where <type> should be one of (feat|fix|ci|chore|docs|test|style|refactor|perf|build|revert)" >&2
+	echo 'Some valid examples: "feat: add support for PyTorch" and "fix(cli): add missing arguments of bentoml serve"'
+	echo "You can read more details about commit message formatting in DEVELOPMENT.md "
+	exit 1
 fi
diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -4,25 +4,21 @@ LC_ALL=C
 GIT_ROOT="$(git rev-parse --show-toplevel)"
 
 LOCAL_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
-VALID_BRANCH_REGEX="^(style|chore|refactor|feat|internal|bugfix|improvement|library|prerelease|release|hotfix)\/[a-zA-Z0-9._-]+$"
+VALID_BRANCH_REGEX="^(style|chore|refactor|feat|internal|bugfix|ci|improvement|library|prerelease|release|hotfix)\/[a-zA-Z0-9._-]+$"
 
 cd "$GIT_ROOT" || exit
 
 # format setup.cfg
-setup-cfg-fmt --max-py-version 3.9 "$GIT_ROOT/setup.cfg"
+setup-cfg-fmt --max-py-version 3.10 "$GIT_ROOT/setup.cfg" && git add "$GIT_ROOT/setup.cfg"
 
 # Run format scripts
 # ./scripts/tools/formatter.sh || exit 1
 
-for f in $(find .github/ -type f -name '*.yml'); do
-  yamllint -c "$GIT_ROOT"/.yamllint.yml "$f" || exit 1
-done
+find .github -type f -name '*.yml' -exec yamllint -c "$GIT_ROOT"/.yamllint.yml {} \; || exit 1
 
-if [[ ! "$LOCAL_BRANCH" =~ $VALID_BRANCH_REGEX ]]
-then
-    printf "Branch name %s doesn't follow the predefined format...\n" "$LOCAL_BRANCH"
-    printf "We aren't going to abort the commit, but we recommend that branch name should adhere to the following format:\n\t%s.\n" "$VALID_BRANCH_REGEX"
-    printf "To rename your branch to follow the format do \`git branch -m 'feature/%s'\`\n" "$LOCAL_BRANCH"
+if [[ ! "$LOCAL_BRANCH" =~ $VALID_BRANCH_REGEX ]]; then
+	printf "Branch name %s doesn't follow the predefined format...\n" "$LOCAL_BRANCH"
+	printf "We aren't going to abort the commit, but we recommend that branch name should adhere to the following format:\n\t%s.\n" "$VALID_BRANCH_REGEX"
+	printf "To rename your branch to follow the format do \`git branch -m 'feature/%s'\`\n" "$LOCAL_BRANCH"
 fi
 exit 0
-
diff --git a/hooks/prepare-commit-msg b/hooks/prepare-commit-msg
--- a/hooks/prepare-commit-msg
+++ b/hooks/prepare-commit-msg
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/usr/bin/env bash
 # A git hook to block an unsigned-off commit
 
 COMMIT_MSG_FILE=$1
@@ -7,9 +7,9 @@ signoff_pattern="Signed-off-by: .+ <.+@.+>"
 commit_message=$(cat "$COMMIT_MSG_FILE")
 
 if [[ ! "$commit_message" =~ $signoff_pattern ]]; then
-  echo "Aborted \`git commit\` because it's not signed-off."
-  echo "You can sign-off your commit using the \`-s\` flag as follow:"
-  echo
-  echo "git commit -sm <commit message>"
-  exit 1
+	echo "Aborted \`git commit\` because it's not signed-off."
+	echo "You can sign-off your commit using the \`-s\` flag as follow:"
+	echo
+	echo "git commit -sm <commit message>"
+	exit 1
 fi
