chore: cleanup repo
Signed-off-by: Aaron Pham <29749331+aarnphm@users.noreply.github.com>

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -5,13 +5,13 @@ local_branch="$(git rev-parse --abbrev-ref HEAD)"
 
 valid_branch_regex="^(chore|refactor|feat|feature|bugfix|improvement|library|prerelease|release|hotfix)\/[a-zA-Z0-9._-]+$"
 
-
-if [[ ! $local_branch =~ $valid_branch_regex ]]
-then
-    printf "Invalid branch name $local_branch, Aborting commits...\n"
-    printf "Branch names in this project must adhere to the following format:\n\t$valid_branch_regex.\n"
-    printf "To rename your branch to follow the format do \`git branch -m 'feature/$local_branch'\`\n"
-    exit 1
+if [ $local_branch != "bentoml-1.0" ]; then
+    if [[ ! $local_branch =~ $valid_branch_regex ]]
+    then
+        printf "Invalid branch name $local_branch, Aborting commits...\n"
+        printf "Branch names in this project must adhere to the following format:\n\t$valid_branch_regex.\n"
+        printf "To rename your branch to follow the format do \`git branch -m 'feature/$local_branch'\`\n"
+        exit 1
+    fi
+    exit 0
 fi
-
-exit 0
