feat: rewrote advanced guides for containerization and add autoescape for jinja templates environment
Signed-off-by: Aaron Pham <29749331+aarnphm@users.noreply.github.com>

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -4,7 +4,7 @@ LC_ALL=C
 GIT_ROOT="$(git rev-parse --show-toplevel)"
 
 LOCAL_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
-VALID_BRANCH_REGEX="^(qa|style|chore|refactor|feat|internal|bugfix|improvement|library|prerelease|release|hotfix)\/[a-zA-Z0-9._-]+$"
+VALID_BRANCH_REGEX="^(qa|style|chore|refactor|feat|internal|bugfix|improvement|library|docs|prerelease|release|hotfix)\/[a-zA-Z0-9._-]+$"
 
 cd "$GIT_ROOT" || exit
 
@@ -17,17 +17,17 @@ setup-cfg-fmt --max-py-version 3.10 "$GIT_ROOT/setup.cfg"
 git diff --name-status | grep setup.cfg &>/dev/null && git add setup.cfg
 
 # Run format scripts
-./scripts/tools/formatter.sh || exit 1
+./scripts/tools/formatter.sh && git add . || exit 1
 
 INFO "Running yamllint on github workflow..."
-for f in $(find .github/ -type f -name '*.yml'); do
+for f in $(find .github -type f -name '*.yml'); do
 	yamllint -c "$GIT_ROOT"/.yamllint.yml "$f" || exit 1
 done
 
 INFO "Running branch name validation..."
 if [[ ! "$LOCAL_BRANCH" =~ $VALID_BRANCH_REGEX ]]; then
-	WARN "Branch name %s doesn't follow the predefined format...\n" "$LOCAL_BRANCH"
-	WARN "We aren't going to abort the commit, but we recommend that branch name should adhere to the following format:\n\t%s.\n" "$VALID_BRANCH_REGEX"
-	WARN "To rename your branch to follow the format do \`git branch -m 'feature/%s'\`\n" "$LOCAL_BRANCH"
+	WARN "Branch name $LOCAL_BRANCH doesn't follow the predefined format...\n"
+	WARN "We aren't going to abort the commit, but we recommend that branch name should adhere to the following format:\n\t$VALID_BRANCH_REGEX.\n"
+	WARN "To rename your branch to follow the format do \`git branch -m 'feature/$LOCAL_BRANCH'\`\n"
 fi
 exit 0
