attempt to fix CI

diff --git a/.github/workflows/cqa.yml b/.github/workflows/cqa.yml
--- a/.github/workflows/cqa.yml
+++ b/.github/workflows/cqa.yml
@@ -3,14 +3,14 @@ on:
   push:
     branches: [main]
     paths-ignore:
-      - 'docs/**'
-      - 'bazel/**'
+      - 'bentoml/docs/**'
+      - 'bentoml/bazel/**'
       - 'typings/**'
   pull_request:
     paths-ignore:
-      - 'docs/**'
-      - 'bazel/**'
-      - 'typings/**'
+      - 'bentoml/docs/**'
+      - 'bentoml/bazel/**'
+      - 'bentoml/typings/**'
   schedule:
     - cron: '0 0 * * 1/2'
 env:
@@ -38,7 +38,7 @@ jobs:
       - name: Install libenchant
         run: sudo apt-get update && sudo apt-get install -y libenchant-2-dev
       - name: Install dependencies
-        run: pdm sync -dG docs
+        run: pdm sync -dG bentoml-docs
       - name: Run spellcheck script
         run: |
-          pdm run -v sphinx-build -b spelling ./docs/source ./docs/build || (echo "Failed to run spellcheck. Refer to logs for more details"; exit 1)
+          pdm run -p bentoml -v sphinx-build -b spelling ./docs/source ./docs/build || (echo "Failed to run spellcheck. Refer to logs for more details"; exit 1)
