Create transformers unit test

diff --git a/.github/workflows/frameworks.yml b/.github/workflows/frameworks.yml
--- a/.github/workflows/frameworks.yml
+++ b/.github/workflows/frameworks.yml
@@ -1278,6 +1278,16 @@ jobs:
           pip install .
           pip install -r requirements/tests-requirements.txt
 
+      - name: Run unit test for transformers
+        shell: bash
+        run: |
+          OPTS=(--cov=bentoml --cov-config=./setup.cfg --cov-report=xml:"transformers.unit.xml" --cov-report term-missing:skip-covered)
+          python -m pytest ./tests/integration/frameworks/test_transformers_unit.py "${OPTS[@]}" || ERR=1
+          if [ $ERR -eq 1 ]; then
+            echo "unit tests for transformers failed!"
+            exit 1
+          fi
+
       - name: Run tests and generate coverage report
         run: make tests-transformers
         shell: bash
