feat: add tests for no eager execution
Signed-off-by: Aaron Pham <29749331+aarnphm@users.noreply.github.com>

diff --git a/.github/workflows/frameworks.yml b/.github/workflows/frameworks.yml
--- a/.github/workflows/frameworks.yml
+++ b/.github/workflows/frameworks.yml
@@ -1218,12 +1218,32 @@ jobs:
         run: make tests-tensorflow_v2
         shell: bash
 
+      - name: Run unit test for tensorflow_v2
+        shell: bash
+        run: |
+          OPTS=(--cov=bentoml --cov-config=./setup.cfg --cov-report=xml:"tf2.unit.xml" --cov-report term-missing:skip-covered)
+          python -m pytest ./tests/integration/frameworks/test_tensorflow_v2_unit.py "${OPTS[@]}" || ERR=1
+          if [ $ERR -eq 1 ]; then
+            echo "unit tests for tensorflow_v2 failed!"
+            exit 1
+          fi
+
+      - name: Run tensorflow_v2 without eager execution
+        shell: bash
+        run: |
+          OPTS=(--cov=bentoml --cov-config=./setup.cfg --cov-report=xml:"tf2.unit.no_eager.xml" --cov-report term-missing:skip-covered --disable-eager-execution)
+          python -m pytest ./tests/integration/frameworks/test_tensorflow_v2_unit.py "${OPTS[@]}" || ERR=1
+          if [ $ERR -eq 1 ]; then
+            echo "unit tests for tensorflow_v2 failed!"
+            exit 1
+          fi
+
       - name: Upload test coverage to Codecov
-        if: ${{ needs.diff.outputs.tf2 == 'true' }}
+        if: ${{ needs.diff.outputs.tensorflow_v2 == 'true' }}
         uses: codecov/codecov-action@v2
         with:
           directory: ./
-          files: ./tf2.xml
+          files: ./tf2.xml,./tf2.unit.xml,./tf2.unit.no_eager.xml
           flags: tensorflow
           verbose: true
 
